site_name: Farmshare

theme: readthedocs

extra_css:
  - style.css

markdown_extensions:
    - smarty
    - toc:
        permalink: True
    - sane_lists
    - fenced_code

nav:
  - Introduction: index.md
  - "Getting Connected": connected.md
  - "Using Software": software.md
  - "Adding Capacity": capacity.md
