site_name: FarmShare

theme: readthedocs

extra_css:
  - style.css

markdown_extensions:
    - admonition
    - fenced_code
    - nl2br
    - smarty
    - tables
    - toc:
        permalink: True

nav:
  - Introduction: index.md
  - "Getting Connected": connecting.md
  - "Running Jobs": slurm.md
  - "Using Software": software.md
  - "Adding Capacity": capacity.md
  - Policy: policy.md
